ALTER TABLE camera_owners
  ADD COLUMN IF NOT EXISTS head_full_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS head_position VARCHAR(255),
  ADD COLUMN IF NOT EXISTS head_phone VARCHAR(50),
  ADD COLUMN IF NOT EXISTS head_email VARCHAR(255);
